[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version="0.8.30"
evm_version = "paris"
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@foundry-devops/=lib/foundry-devops/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
